### PR TITLE
fix the ParseGas maxFeeGwei param

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
ping @bonedaddy

**Review by DaveedL — APPROVED** [review]

**Comment by krasi-georgiev** [comment]
ping @bonedaddy

**Comment by krasi-georgiev** [comment]
ping @bonedaddy

**Comment by krasi-georgiev** [comment]
ping @bonedaddy

**Comment by krasi-georgiev** [comment]
no reply from the maintainer

**Pull request closed without merging**
