### PR TITLE
Some refactorings

### PR DESCRIPTION
**Pull request by krasi-georgiev**
- Add some more json fields  - Tx Timestamp,Tx PendingTimeStamp
 - handle response for Initialize …
 - Add and print error reason …
- Added event subscription methos …
- Remove the mutex as this blocks closing the client …
- Proper parsing for filters …
- added an example for subscription to a function call.

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Review by bonedaddy — CHANGES_REQUESTED** [review]
Mutex cant be removed, it must be used due to concurrency limitations with the gorilla websockets libray, otherwise there will be data races.

If the client blocks on closing it is indicative that there are active goroutines that have the mutex lock. You should use a context cancellation pattern such that context is cancelled, which is picked up by active goroutines who then exit.

All other changes look good however :+1:

**Comment by krasi-georgiev** [comment]
Yep I also would prefer to use a context, but as you can see the `ReadJSON` function call doesn't accept a context.
https://github.com/bonedaddy/go-blocknative/pull/8/files?w=1#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09R109

I think the solution for now would be to use one mutex for reading and another one for writing, this should solve the problem.

**Comment by bonedaddy** [comment]
That sounds like a good idea :rocket:

**Comment by krasi-georgiev** [comment]
ok I will refactor and will push next week.

**Comment by krasi-georgiev** [comment]
ok added the mutex and it works as expected

**Comment by krasi-georgiev** [comment]
ping

**Comment by krasi-georgiev** [comment]
@bonedaddy ping

**Comment by krasi-georgiev** [comment]
@bonedaddy ping

**Review by bonedaddy — APPROVED** [review]
Looks good! apologies for the delay have had a few very busy weeks.

**Comment by krasi-georgiev** [comment]
no problem, thanks

**Pull request merged**
